# Generated by Django 4.2.16 on 2024-11-22 14:22

import anagrafiche.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragionesociale', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('sito_web', models.CharField(blank=True, max_length=200, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('categoria', models.CharField(choices=[('nessuna', 'Manca categoria'), ('pelli', 'Pelli'), ('macello', 'Macello'), ('prodotti chimici', 'Prodotti Chimici'), ('lavorazioni esterne', 'Lavorazioni Esterne'), ('servizi', 'Servizi'), ('manutenzioni', 'Manutenzioni'), ('rifiuti', 'Rifiuti')], default='nessuna', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ragionesociale'],
            },
        ),
        migrations.CreateModel(
            name='FornitoreLavorazioniEsterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='fornitore_ptr_lavorazioniesterne', to='anagrafiche.fornitore')),
                ('is_lwg', models.BooleanField(default=False)),
                ('audit', models.CharField(choices=[('not_audited', 'Nessun Audit'), ('leather_manufacturer_audit_protocol', 'Leather Manufacturer Audit Protocol'), ('subcontractor_audit_protocol', 'Subcontractor Audit Protocol'), ('mini_audit_protocol', 'Mini-Audit Protocol')], default='not_audited', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FornitoreManutenzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='fornitore_ptr_manutenzioni', to='anagrafiche.fornitore')),
                ('prova', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FornitoreProdottiChimici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='fornitore_ptr_prodottichimici', to='anagrafiche.fornitore')),
                ('id_zdhc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FornitoreServizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='fornitore_ptr_servizi', to='anagrafiche.fornitore')),
                ('prova', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LwgFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwg_urn', models.CharField(max_length=50)),
                ('lwg_score', models.CharField(blank=True, max_length=50, null=True)),
                ('lwg_range', models.CharField(blank=True, max_length=100, null=True)),
                ('lwg_date', models.DateField(blank=True, null=True)),
                ('lwg_expiry', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='lwg_certificates/')),
                ('fk_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='TransferValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='FornitorePelli',
            fields=[
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_pelli', serialize=False, to='anagrafiche.fornitore')),
                ('is_lwg', models.BooleanField(default=False)),
                ('urn', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_fornitore', models.CharField(blank=True, choices=[('macello', 'Macello'), ('commerciante', 'Commerciante'), ('altro', 'Altro')], max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            bases=('anagrafiche.fornitore',),
        ),
        migrations.CreateModel(
            name='FornitoreRifiuti',
            fields=[
                ('fornitore_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_rifiuti', serialize=False, to='anagrafiche.fornitore')),
            ],
            bases=('anagrafiche.fornitore',),
        ),
        migrations.CreateModel(
            name='Macello',
            fields=[
                ('fornitore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anagrafiche.fornitore')),
                ('is_group', models.BooleanField(default=False)),
            ],
            bases=('anagrafiche.fornitore',),
        ),
        migrations.CreateModel(
            name='XrTransferValueLwgFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrtransfervaluelwgfornitore', to=settings.AUTH_USER_MODEL)),
                ('fk_lwgcertificato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.lwgfornitore')),
                ('fk_transfervalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.transfervalue')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragionesociale', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ragionesociale'],
            },
        ),
        migrations.CreateModel(
            name='XrDocumentiTrasportatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(upload_to=anagrafiche.models.trasportatore_documenti_upload_to)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_trasportatore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Trasportatore',
            },
        ),
        migrations.CreateModel(
            name='XrDocumentiSmaltitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(upload_to=anagrafiche.models.smaltitore_documenti_upload_to)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_smaltitore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Smaltitore',
            },
        ),
        migrations.CreateModel(
            name='XrDocumentiGestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=anagrafiche.models.gestore_documenti_upload_to)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_gestore', to=settings.AUTH_USER_MODEL)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_gestore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Gestore',
            },
        ),
    ]
