# Generated by Django 4.2.16 on 2024-11-25 16:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_fornitore_fornitorelavorazioniesterne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinazioniDiverseFornitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragionesociale', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('fk_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore')),
            ],
            options={
                'ordering': ['ragionesociale'],
            },
        ),
    ]
