# Generated by Django 4.2.16 on 2024-11-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_destinazionidiversefornitori'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DestinazioniDiverseFornitori',
            new_name='DestinazioneDiversaFornitore',
        ),
    ]
