# Generated by Django 4.2.16 on 2024-11-25 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0004_rename_destinazionidiversefornitori_destinazionediversafornitore'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinazionediversafornitore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinazionediversafornitore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinazione_diversa_fornitore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinazionediversafornitore',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinazionediversafornitore',
            name='fk_fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinazione_diversa_fornitore', to='anagrafiche.fornitore'),
        ),
    ]
