# Generated by Django 4.2.16 on 2024-11-22 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0002_fornitore_fornitorelavorazioniesterne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('scheda_tecnica', models.FileField(blank=True, null=True, upload_to='schede_tecniche_articoli/')),
                ('industries_served', models.CharField(blank=True, choices=[('apparel/clothing', 'Apparel/clothing'), ('automotive', 'Automotive'), ('contract', 'Contract'), ('footwear', 'Footwear'), ('footwear (athletic)', 'Footwear (Athletic)'), ('leather goods', 'Leather goods'), ('upholstery', 'Upholstery')], max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articolo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'articoli',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='ElencoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('norma_riferimento', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elenco_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'elenco test',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='LavorazioneEsterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('codice', models.CharField(max_length=9)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavorazione_esterna', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lavorazioni esterne',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='ListinoTerzista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listino_terzista', to=settings.AUTH_USER_MODEL)),
                ('fk_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore')),
                ('fk_lavorazione_esterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.lavorazioneesterna')),
            ],
        ),
        migrations.CreateModel(
            name='TestArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(blank=True, max_length=100, null=True)),
                ('interno_esterno', models.CharField(blank=True, choices=[('interno', 'Interno'), ('esterno', 'Esterno')], max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_articolo', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_articolo', to='articoli.articolo')),
                ('fk_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_articolo', to='articoli.elencotest')),
            ],
        ),
        migrations.CreateModel(
            name='Procedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_procedura', models.IntegerField(blank=True, null=True)),
                ('data_procedura', models.DateField(default=django.utils.timezone.now)),
                ('nr_revisione', models.IntegerField(blank=True, null=True)),
                ('data_revisione', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articolo')),
            ],
        ),
        migrations.CreateModel(
            name='PrezzoListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateField(default=datetime.date.today)),
                ('prezzo', models.DecimalField(decimal_places=3, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prezzo_listino', to=settings.AUTH_USER_MODEL)),
                ('fk_listino_terzista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezzo', to='articoli.listinoterzista')),
            ],
            options={
                'ordering': ['-data_inserimento'],
            },
        ),
        migrations.CreateModel(
            name='ListinoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=3, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listino_cliente', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listino_cliente', to='articoli.articolo')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listino_cliente', to='anagrafiche.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FaseLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('interno_esterno', models.CharField(blank=True, choices=[('interno', 'Interno'), ('esterno', 'Esterno')], max_length=10, null=True)),
                ('um', models.CharField(blank=True, choices=[('mq', 'Mq.'), ('Nr.', 'Nr.'), ('Kg.', 'Kg.')], max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faselavoro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'fasi lavoro',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioProcedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interna', models.BooleanField(default=True)),
                ('numero_riga', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglioprocedura', to=settings.AUTH_USER_MODEL)),
                ('fk_faselavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.faselavoro')),
                ('fk_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore')),
                ('fk_procedura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.procedura')),
            ],
            options={
                'verbose_name_plural': 'dettaglio procedure',
                'ordering': ['numero_riga'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioFaseLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributo', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettagliofaselavoro', to=settings.AUTH_USER_MODEL)),
                ('fk_fase_lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.faselavoro')),
            ],
        ),
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'colori',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='CaratteristicaProcedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('numero_riga', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caratteristicaprocedura', to=settings.AUTH_USER_MODEL)),
                ('fk_dettaglio_fase_lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.dettagliofaselavoro')),
                ('fk_dettaglio_procedura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.dettaglioprocedura')),
                ('fk_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='anagrafiche.fornitore')),
                ('fk_lavorazione_esterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.lavorazioneesterna')),
            ],
        ),
    ]
