# Generated by Django 4.2.16 on 2024-11-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articoli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('codice', models.CharField(max_length=9)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavorazione', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lavorazioni',
                'ordering': ['descrizione'],
            },
        ),
        migrations.RemoveField(
            model_name='caratteristicaprocedura',
            name='fk_lavorazione_esterna',
        ),
        migrations.RemoveField(
            model_name='listinoterzista',
            name='fk_lavorazione_esterna',
        ),
        migrations.DeleteModel(
            name='LavorazioneEsterna',
        ),
        migrations.AddField(
            model_name='caratteristicaprocedura',
            name='fk_lavorazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.lavorazione'),
        ),
        migrations.AddField(
            model_name='listinoterzista',
            name='fk_lavorazione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articoli.lavorazione'),
            preserve_default=False,
        ),
    ]
