# Generated by Django 4.2.16 on 2024-11-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0002_lavorazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinoterzista',
            name='fk_lavorazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.lavorazione'),
        ),
    ]
