# Generated by Django 4.2.16 on 2024-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0002_remove_lotto_fk_tipogrezzo_taglio_spessore_sezione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglio',
            name='descrizione',
            field=models.CharField(max_length=10),
        ),
    ]
