# Generated by Django 4.2.16 on 2024-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0003_alter_taglio_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concia',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quality',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spessore',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taglio',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoanimale',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
    ]
