# Generated by Django 4.2.16 on 2024-11-07 19:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_sito", models.CharField(max_length=100)),
                ("logo", models.ImageField(default="avatar.png", upload_to="logo")),
                ("urn", models.CharField(blank=True, max_length=50, null=True)),
                ("piva", models.CharField(blank=True, max_length=11, null=True)),
                ("indirizzo", models.CharField(blank=True, max_length=100, null=True)),
                ("cap", models.CharField(blank=True, max_length=5, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("provincia", models.CharField(blank=True, max_length=2, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "primary_cat",
                    models.CharField(
                        choices=[
                            ("Nessuna categoria", "Nessuna categoria"),
                            (
                                "A - Raw hide/skin to tanned",
                                "A - Raw hide/skin to tanned",
                            ),
                            (
                                "B - Raw hide/skin to crust",
                                "B - Raw hide/skin to crust",
                            ),
                            (
                                "C - Raw hide/skin to finished leather",
                                "C - Raw hide/skin to finished leather",
                            ),
                            (
                                "D - Tanned hide/skin to finished leather",
                                "D - Tanned hide/skin to finished leather",
                            ),
                            (
                                "E - Crust hide/skin to finished leather",
                                "E - Crust hide/skin to finished leather",
                            ),
                            (
                                "F - Tanned hide/skin to crust leather",
                                "F - Tanned hide/skin to crust leather",
                            ),
                            (
                                "G - Raw hide/skin to pickled/pre-tanned material",
                                "G - Raw hide/skin to pickled/pre-tanned material",
                            ),
                        ],
                        default="Nessuna categoria",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_cat",
                    models.CharField(
                        choices=[
                            ("Nessuna categoria", "Nessuna categoria"),
                            (
                                "A - Raw hide/skin to tanned",
                                "A - Raw hide/skin to tanned",
                            ),
                            (
                                "B - Raw hide/skin to crust",
                                "B - Raw hide/skin to crust",
                            ),
                            (
                                "C - Raw hide/skin to finished leather",
                                "C - Raw hide/skin to finished leather",
                            ),
                            (
                                "D - Tanned hide/skin to finished leather",
                                "D - Tanned hide/skin to finished leather",
                            ),
                            (
                                "E - Crust hide/skin to finished leather",
                                "E - Crust hide/skin to finished leather",
                            ),
                            (
                                "F - Tanned hide/skin to crust leather",
                                "F - Tanned hide/skin to crust leather",
                            ),
                            (
                                "G - Raw hide/skin to pickled/pre-tanned material",
                                "G - Raw hide/skin to pickled/pre-tanned material",
                            ),
                        ],
                        default="Nessuna categoria",
                        max_length=50,
                    ),
                ),
                (
                    "tertiary_cat",
                    models.CharField(
                        choices=[
                            ("Nessuna categoria", "Nessuna categoria"),
                            (
                                "A - Raw hide/skin to tanned",
                                "A - Raw hide/skin to tanned",
                            ),
                            (
                                "B - Raw hide/skin to crust",
                                "B - Raw hide/skin to crust",
                            ),
                            (
                                "C - Raw hide/skin to finished leather",
                                "C - Raw hide/skin to finished leather",
                            ),
                            (
                                "D - Tanned hide/skin to finished leather",
                                "D - Tanned hide/skin to finished leather",
                            ),
                            (
                                "E - Crust hide/skin to finished leather",
                                "E - Crust hide/skin to finished leather",
                            ),
                            (
                                "F - Tanned hide/skin to crust leather",
                                "F - Tanned hide/skin to crust leather",
                            ),
                            (
                                "G - Raw hide/skin to pickled/pre-tanned material",
                                "G - Raw hide/skin to pickled/pre-tanned material",
                            ),
                        ],
                        default="Nessuna categoria",
                        max_length=50,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("site_area", models.FloatField(blank=True, null=True)),
                ("facility_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacilityContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            (
                                "6a - Principal Contact Name and position",
                                "6a - Principal Contact Name and position",
                            ),
                            (
                                "6b - Ultimately responsible for environmental issue at this site",
                                "6b - Ultimately responsible for environmental issue at this site",
                            ),
                            (
                                "6c - Responsible on a day-to-day basis for environmental issue at this site",
                                "6c - Responsible on a day-to-day basis for environmental issue at this site",
                            ),
                            ("7 - Others", "7 - Others"),
                        ],
                        default="7 - Others",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "fk_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="anagrafiche.facility",
                    ),
                ),
            ],
        ),
    ]
