# Generated by Django 4.2.16 on 2024-11-22 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0002_fornitore_fornitorelavorazioniesterne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('classe_processo', models.CharField(choices=[('Direzionale', 'Direzionale'), ('Principale', 'Principale'), ('Supporto', 'Supporto')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_audit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rapporto_audit', models.PositiveIntegerField(editable=False)),
                ('data_rapporto_audit', models.DateField()),
                ('norme_riferimento', models.TextField(blank=True, null=True)),
                ('auditor', models.TextField(blank=True, null=True)),
                ('risultato', models.TextField(blank=True, null=True)),
                ('data_controllo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporto_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_rapporto_audit'],
            },
        ),
        migrations.CreateModel(
            name='RapportoNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nc', models.PositiveIntegerField(editable=False)),
                ('data_nc', models.DateField()),
                ('tipo_nc', models.CharField(choices=[('NC di Sistema', 'NC di Sistema'), ('NC di Produzione', 'NC di Produzione'), ('NC da Cliente', 'NC da Cliente'), ('NC a Fornitore', 'NC a Fornitore'), ('NC Aspetti Ambientali', 'NC Aspetti Ambientali'), ('Commento', 'Commento')], max_length=50)),
                ('segnalato_da', models.CharField(choices=[('Cliente', 'Cliente'), ('Fornitore', 'Fornitore'), ('Interno', 'Interno')], max_length=50)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('causa_radice', models.TextField(blank=True, null=True)),
                ('settore_responsabile', models.CharField(blank=True, max_length=100, null=True)),
                ('decisioni_immediate', models.CharField(choices=[('Accettare', 'Accettare'), ('Rilavorare', 'Rilavorare'), ('Scartare', 'Scartare'), ('Sostituire', 'Sostituire'), ('Altro', 'Altro')], max_length=50)),
                ('note_decisioni_immediate', models.TextField(blank=True, null=True)),
                ('responsabile_decisione_immediata', models.CharField(blank=True, max_length=50, null=True)),
                ('data_limite_decisione_immediata', models.DateField(blank=True, null=True)),
                ('is_ac_necessaria', models.BooleanField(default=False)),
                ('descrizione_ac', models.TextField(blank=True, null=True)),
                ('responsabile_ac', models.CharField(blank=True, max_length=50, null=True)),
                ('data_limite_ac', models.DateField(blank=True, null=True)),
                ('is_ac_completa', models.BooleanField(default=False)),
                ('is_ac_efficace', models.BooleanField(default=False)),
                ('altre_decisioni_ac', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapportornc', to=settings.AUTH_USER_MODEL)),
                ('fk_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.cliente')),
                ('fk_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.fornitore')),
                ('fk_rapportoaudit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonconformity.rapportoaudit')),
            ],
            options={
                'ordering': ['-data_nc'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('fk_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity.processo')),
                ('fk_rapportoaudit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity.rapportoaudit')),
            ],
        ),
    ]
