# Generated by Django 4.2.16 on 2024-11-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavorazioni', '0002_prezzolavorazione_listinoprezzilavorazioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prezzolavorazione',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prezzolavorazione',
            name='fk_lavorazione',
        ),
        migrations.DeleteModel(
            name='ListinoPrezziLavorazioni',
        ),
        migrations.DeleteModel(
            name='PrezzoLavorazione',
        ),
    ]
