# Generated by Django 4.2.16 on 2024-11-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavorazioni', '0003_remove_prezzolavorazione_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lavorazione',
        ),
    ]
