# Generated by Django 4.2.16 on 2024-11-25 16:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0003_destinazionidiversefornitori'),
        ('lavorazioni', '0004_delete_lavorazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaleTrasporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causali_trasporto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'causali trasporto',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='PortoMateriale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('decrizione_inglese', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porto_materiale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'aspetto dei beni',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='OrdineLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_est', models.CharField(choices=[('interno', 'Interno'), ('esterno', 'Esterno')], default='interno', max_length=10)),
                ('num_doc', models.IntegerField(default=None)),
                ('data_doc', models.DateField(default=datetime.date.today)),
                ('trasporto', models.CharField(choices=[('mittente', 'Mittente'), ('vettore', 'Vettore'), ('destinatario', 'Destinatario')], default='mittente', max_length=20)),
                ('n_colli', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordine_lavoro', to=settings.AUTH_USER_MODEL)),
                ('fk_causale_trasporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordine_lavoro', to='lavorazioni.causaletrasporto')),
                ('fk_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordine_lavoro', to='anagrafiche.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='AspettoDeiBeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspetto_beni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'aspetto dei beni',
                'ordering': ['descrizione'],
            },
        ),
    ]
