# Generated by Django 4.2.16 on 2024-11-25 20:28

import datetime
from django.db import migrations, models
import lavorazioni.models


class Migration(migrations.Migration):

    dependencies = [
        ('lavorazioni', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinelavoro',
            name='data_inizio_trasporto',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ordinelavoro',
            name='ora_inizio_trasporto',
            field=models.TimeField(default=lavorazioni.models.get_current_time),
        ),
    ]
