# Generated by Django 4.2.16 on 2024-11-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_destinazionediversafornitore_created_at_and_more'),
        ('lavorazioni', '0006_ordinelavoro_data_inizio_trasporto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinelavoro',
            name='fk_vettore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordine_lavoro_vettore', to='anagrafiche.fornitore'),
        ),
    ]
