# Generated by Django 4.2.16 on 2024-11-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0005_dettagliolotto'),
        ('anagrafiche', '0005_destinazionediversafornitore_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articoli', '0002_lavorazione_and_more'),
        ('lavorazioni', '0007_ordinelavoro_fk_vettore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DettaglioOrdineLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_lavoro', to=settings.AUTH_USER_MODEL)),
                ('fk_dettaglio_lotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_lavoro', to='acquistopelli.dettagliolotto')),
                ('fk_lavorazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_lavoro', to='articoli.lavorazione')),
                ('fk_ordine_lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_lavoro', to='lavorazioni.ordinelavoro')),
            ],
        ),
        migrations.CreateModel(
            name='OutputLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(choices=[('consegna fatturabile', 'Consegna fatturabile'), ('consegna non fatturabile', 'Consegna non fatturabile'), ('restituzione fatturabile', 'Restituzione fatturabile'), ('scarto non fatturabile', 'Scarto non fatturabile'), ('bolla fattura subfornitore', 'Bolla fattura subfornitore')], default='consegna fatturabile', max_length=50)),
                ('n_doc_reso', models.IntegerField(default=None)),
                ('data_doc_reso', models.DateField()),
                ('quantity_output', models.IntegerField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=3, max_digits=8)),
                ('valore_output', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_scarto', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to=settings.AUTH_USER_MODEL)),
                ('fk_concia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.concia')),
                ('fk_dettaglio_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_lavorazione', to='lavorazioni.dettaglioordinelavoro')),
                ('fk_fornitore_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione_dest', to='anagrafiche.fornitore')),
                ('fk_fornitore_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_lavorazione', to='anagrafiche.fornitore')),
                ('fk_lavorazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='articoli.lavorazione')),
                ('fk_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.quality')),
                ('fk_sezione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.sezione')),
                ('fk_spessore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.spessore')),
                ('fk_taglio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.taglio')),
                ('fk_tipoanimale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_lavorazione', to='acquistopelli.tipoanimale')),
            ],
        ),
        migrations.AddField(
            model_name='dettaglioordinelavoro',
            name='fk_output_lavorazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_lavoro', to='lavorazioni.outputlavorazione'),
        ),
    ]
