# Generated by Django 4.2.16 on 2024-11-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_destinazionediversafornitore_created_at_and_more'),
        ('lavorazioni', '0008_dettaglioordinelavoro_outputlavorazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinelavoro',
            name='fk_aspetto_beni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_lavoro', to='lavorazioni.aspettodeibeni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordinelavoro',
            name='fk_destinazione_diversa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_lavoro', to='anagrafiche.destinazionediversafornitore'),
            preserve_default=False,
        ),
    ]
