# Generated by Django 4.2.16 on 2024-11-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lavorazioni', '0009_ordinelavoro_fk_aspetto_beni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitaMisura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('abbreviazione', models.CharField(max_length=2)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unita_misura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'unità di misura',
                'ordering': ['descrizione'],
            },
        ),
    ]
