# Generated by Django 4.2.16 on 2024-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavorazioni', '0011_dettaglioordinelavoro_fk_unita_misura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioordinelavoro',
            name='descrizione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
