# Generated by Django 4.2.16 on 2024-11-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavorazioni', '0014_rename_decrizione_inglese_portomateriale_descrizione_inglese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioordinelavoro',
            name='fk_ordine_lavoro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ordine_lavoro', to='lavorazioni.ordinelavoro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portomateriale',
            name='descrizione_inglese',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
