# Generated by Django 4.2.16 on 2024-11-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0005_dettagliolotto'),
        ('lavorazioni', '0015_alter_dettaglioordinelavoro_fk_ordine_lavoro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputlavorazione',
            name='fk_dettaglio_lotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='output_lavorazione', to='acquistopelli.dettagliolotto'),
            preserve_default=False,
        ),
    ]
