# Generated by Django 4.2.16 on 2024-11-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_destinazionediversafornitore_created_at_and_more'),
        ('lavorazioni', '0016_outputlavorazione_fk_dettaglio_lotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinelavoro',
            name='fk_destinazione_diversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordine_lavoro', to='anagrafiche.destinazionediversafornitore'),
        ),
    ]
